### ISSUE TITLE
No results are shown

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/alfred_dvb#17]
All I've been getting for a little while now is

> Keine Haltestelle oder Verbindungen gefunden 🤔

The odd thing is that no network request seem to be sent. And the API would actually be returning sensible data as well. Not sure what's up here.

**Comment by lutzthies** [comment]
This bug occurred due to some changes in the VVO Widget API that caused every HTTP GET request to return no data at all. See https://github.com/kiliankoe/dvbgo/issues/4

After the corresponding [PR](https://github.com/kiliankoe/dvbgo/pull/7) has been merged the bug will be fixed when rebuilding the workflow with the update dvbgo package.

**Comment by kiliankoe** [comment]
Thanks again, just published a new release here 😊 

https://github.com/kiliankoe/alfred_dvb/releases/tag/1.0.2
